language: python
cache:
  pip: true
  yarn: true
  directories:
    - vibe_ui/node_modules
sudo: required
before_install:
  # manually install yarn for now - https://github.com/travis-ci/travis-ci/issues/6720
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=0.21.3-1
python:
  - "3.4"
  - "3.5"
  - "3.6"
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
# switch to conda due to travis issue with scipy - http://www.camillescott.org/2016/07/15/travis-pytest-scipyconf/
# install: pip install -r requirements.txt
install:
# install python
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pytest pytest-cov coverage
  - source activate test
  - pip install -q -U codecov smbus2 unittest-data-provider flask flask-restful pyyaml requests
  - python setup_travis.py install
# Install node 6 (current LTS as of January 2017)
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 6
  # Install latest npm
  - npm install -g npm
  # Install node deps
  - cd vibe-ui
  - yarn install
  - cd ..
script:
  - PYTHONPATH=. pytest --cov=./
  - cd vibe-ui
  - yarn test -- --coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)